name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Check out code
        uses: actions/checkout@v2
   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_WORKSPACE: pitt-cicd-demo-prod
        working-directory: ./infrastructure

      - name: Terraform Apply
        env:
          TF_WORKSPACE: pitt-cicd-demo-prod
        run: terraform apply -auto-approve
