name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov pytest-env moto
          python -m pip install -e .
      
      - name: Running pytest
        run: |
          pytest --junitxml=TESTS-pytest.xml --cov --cov-report=xml --cov-report=html

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=python.snyk.sarif
          sarif: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: ./infrastructure

      - name: Scan Infrastructure as Code
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
            --sarif-file-output=terraform.snyk.sarif
          sarif: false

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/TESTS-*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}